# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e80dfaa2b431ee0a2087c4ecc41857381d9d1da7a186da8e7b06d0d1dd2bfa7c792a765d0a8f46f5253ca2b4a2b4fa61e5b6e9f5a798947c3a689ac4a6c310
  google_map_lookup: false
  google_map_key: AIzaSyB-YUx2UxhW0v3ouonGnLKMSDGyFt_RuZE

test:
  secret_key_base: 1b22f5f20c56131d9bbf2787384748f264afecbe8c9b7250477c072e6c9dfe8a577102b4c513b9b008f3356ce87d1d376c85dcbd6eb99e0319687b2a46d12f55
  google_map_lookup: false
  google_map_key: AIzaSyB-YUx2UxhW0v3ouonGnLKMSDGyFt_RuZE

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_map_lookup: <%= ENV["GOOGLE_MAP_LOOKUP"] %>
  google_map_key: <%= ENV["GOOGLE_MAP_KEY"] %>